ads/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('ad_list/', views.ad_list, name='ad_list'),
    path('ad_create/', views.ad_create, name='ad_create'),
    path('ad/<int:pk>/delete/', views.ad_delete, name='ad_delete'),
]

django_app/urls.py
from django.urls import path, re_path
from django_app import views

app_name = 'django_app'
urlpatterns = [
    path('', views.home_view, name=''),
    path('index/', views.HomeView.as_view(), name='index'),
    path('home/', views.HomeView.as_view(), name='home'),
    path('home_main/', views.home_main, name='home_main'),


    path('register/', views.register, name='register'),
    path('login/', views.login_, name='login'),
    path('logout/', views.logout_f, name='logout'),


    # path('post/ratings/', views.posts),
    path('post_list/', views.post_list, name='post_list'),
    path('post/<int:pk>/delete/', views.post_delete, name='post_delete'),
    path('post/<int:pk>/detail/', views.post_detail, name='post_detail'),
    path('post/<int:pk>/comment/delete/', views.post_comment_delete, name='post_comment_delete'),
    path('post_create/', views.post_create, name='post_create'),

    path('profile/', views.profile, name='profile'),
    path('profile_update/', views.profileupdate, name='profile_update'),

    path('post_comment_create/<int:pk>/', views.post_comment_create, name='post_comment_create'),

    path('todo/create/', views.todo_create, name='todo_create'),
    path('todo/<int:todo_id>/', views.todo_read, name='todo_read'),
    path('todo/list/', views.todo_read_list, name='todo_read_list'),
    path('todo/<int:todo_id>/update/', views.todo_update, name='todo_update'),
    re_path(r'^todo/(?P<todo_id>\d+)/delete/$', views.todo_delete, name='todo_delete'),

]

django_settings/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),  # grappelli URLS

    path('admin/', admin.site.urls),

    path('', include('django_app.urls')),
    path('', include('ads.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.apps import AppConfig
from .models import profile


class DjangoAppConfig(AppConfig):
    name = 'django_app'

    def ready(self):
        import django_app.signals


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = profile
        fields = ['image', 'description', 'city', 'first', 'second', 'third', 'forth']

django_app/views.py
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.models import User
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from django_app import models
from .forms import ProfileUpdateForm
from django.conf import settings
from django.core.handlers.wsgi import WSGIRequest
from django.utils import timezone


# def logging(controller_func):
#     def wrapper(*args, **kwargs):
#         print(args, kwargs)
#         request: WSGIRequest = args[0]
#         print(request.META)
#
#         models.Logging.objects.create(
#             user=request.user,
#             method=request.method,
#             status=0,
#             url="",
#             description="init"
#         )
#         try:
#             response: HttpResponse = controller_func(*args, **kwargs)
#             if settings.DEBUG_LOG:
#                 models.Logging.objects.create(
#                     user=request.user,
#                     method=request.method,
#                     status=200,
#                     url="",
#                     description="Response: " + str(response.content)
#                 )
#             return response
#         except Exception as error:
#             models.Logging.objects.create(
#                 user=request.user,
#                 method=request.method,
#                 status=500,
#                 url="",
#                 description="Error: " + str(error)
#             )
#             context = {"detail": str(error)}
#             if str(error).find("query does not exist"):
#                 context["extra"] = "Такого объекта не существует"
#             return render(request, "components/error.html", context=context)
#
#     return wrapper


class CustomPaginator:
    @staticmethod
    def paginate(object_list: any, per_page=5, page_number=1):
        paginator_instance = Paginator(object_list=object_list, per_page=per_page)
        try:
            page = paginator_instance.page(number=page_number)
        except PageNotAnInteger:
            page = paginator_instance.page(number=1)
        except EmptyPage:
            page = paginator_instance.page(number=paginator_instance.num_pages)
        return page


class HomeView(View):  # TODO контроллер класс
    template_name = 'django_app/home.html'

    def get(self, request: HttpRequest) -> HttpResponse:
        context = {}
        return render(request, 'django_app/home.html', context=context)

    def post(self, request: HttpRequest) -> HttpResponse:
        context = {}
        return render(request, 'django_app/home.html', context=context)

# @logging
def home_view(request: HttpRequest) -> HttpResponse:  # TODO контроллер функция
    context = {}
    return render(request, 'django_app/home.html', context=context)


def home_main(request: HttpRequest) -> HttpResponse:
    context = {}
    return render(request, 'django_app/home_main.html', context=context)

# @logging
def profile(request):
    return render(request, 'django_app/profile.html')

# @logging
def profileupdate(request):
    if request.method == 'POST':
        pform = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if pform.is_valid:
            pform.save()
            return render(request, 'django_app/profile.html')
    else:
        pform = ProfileUpdateForm(instance=request.user.profile)
    return render(request, 'django_app/profileupdate.html', {'pform': pform})

# @logging
def register(request):
    if request.method == "POST":
        username = request.POST.get("username", "")
        password = request.POST.get("password", "")

        user = User.objects.create_user(username=username, password=password)
        login(request, user)

        return redirect(reverse('django_app:home', args=()))
    return render(request, 'django_app/register.html', context={})

# @logging
def login_(request):
    if request.method == "POST":
        username = request.POST.get("username", "")
        password = request.POST.get("password", "")
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return redirect(reverse('django_app:home_main', args=()))
        else:
            raise Exception("Логин или пароль не верны!")
    return render(request, 'django_app/login.html')

# @logging
def logout_f(request):
    logout(request)
    return redirect(reverse('django_app:login', args=()))

# @logging
def post_create(request: HttpRequest) -> HttpResponse:
    if request.method == "GET":
        context = {}
        return render(request, 'django_app/post_create.html', context=context)
    elif request.method == "POST":
        print("request: ", request)
        # print("request.data: ", request.data)
        print("request.POST: ", request.POST)
        print("request.GET: ", request.GET)
        print("request.META: ", request.META)

        title = request.POST.get('title', None)
        description = request.POST.get('description', "")
        post = models.Post.objects.create(
            title=title,
            description=description,
        )
        return redirect(reverse('django_app:post_list', args=()))

# @logging
def post_list(request: HttpRequest) -> HttpResponse:
    posts = models.Post.objects.all()

    selected_page_number_posts = request.GET.get('page', 1)
    selected_limit_objects_per_page_posts = request.GET.get('limit', 3)
    if request.method == "POST":
        selected_page_number_posts = 1
        selected_limit_objects_per_page_posts = 9999
        search_by_title_posts = request.POST.get('search', None)
        if search_by_title_posts is not None:
            posts = posts.filter(title__contains=str(search_by_title_posts))
        filter_by_user_posts = request.POST.get('filter', None)
        if filter_by_user_posts is not None:
            posts = posts.filter(user=User.objects.get(username=filter_by_user_posts))
    page_posts = CustomPaginator.paginate(
        object_list=posts, per_page=selected_limit_objects_per_page_posts, page_number=selected_page_number_posts
    )

    context = {"page_posts": page_posts, "users": User.objects.all()}
    return render(request, 'django_app/post_list.html', context=context)

# @logging
def post_detail(request: HttpRequest, pk: int) -> HttpResponse:
    post = models.Post.objects.get(id=pk)
    post_comment = models.PostComment.objects.filter(article=post)
    context = {"post": post,
               "comments": post_comment
               }
    return render(request, 'django_app/post_detail.html', context=context)

# @logging
def post_delete(request: HttpRequest, pk: int) -> HttpResponse:
    post = models.Post.objects.get(id=pk)
    post.delete()
    return redirect(reverse('django_app:post_list', args=()))


def post_pk_view(request: HttpRequest, pk: int) -> HttpResponse:
    if request.method == "GET":
        context = {}
        return render(request, 'django_app/post_detail.html', context=context)
    context = {}
    return render(request, 'django_app/post_list.html', context=context)


def post_ph(request, post_id=None):
    print(post_id)
    post_new = models.Post.objects.get(id=post_id)
    comment_new = models.PostComment.objects.filter(article=post_new)
    print(comment_new)
    context = {
        "post": post_new,
        'comments': comment_new
    }
    return render(request, 'django_app/post_detail.html', context)


# @logging
def post_comment_create(request, pk):
    models.PostComment.objects.create(
        article=models.Post.objects.get(id=pk),
        author=request.user,
        description=request.POST.get("description", ""),
    )

    return redirect(reverse('django_app:post_detail', args=(pk,)))

    if request.method == "POST":
        pass
    if request.method == "GET":
        pass

    pass


def post_comment_delete(request: HttpRequest, pk: int) -> HttpResponse:
    comment = models.PostComment.objects.get(id=pk)
    pk = comment.article.id
    comment.delete()
    return redirect(reverse('django_app:post_detail', args=(pk,)))


def todo_create(request):
    if request.method == 'POST':
        title = request.POST.get("title", "")
        description = request.POST.get("description", "")
        models.Todo.objects.create(
            author=User.objects.get(id=1),
            title=title,
            description=description,
            is_completed=False,
        )
        return redirect(reverse('django_app:todo_read_list', args=()))
    context = {
    }
    return render(request, 'django_app/todo_create.html', context)


def todo_read(request, todo_id=None):
    todo = models.Todo.objects.get(id=todo_id)
    context = {
        "todo": todo
    }
    return render(request, 'django_app/todo_detail.html', context)


def todo_read_list(request):

    is_detail_view = request.GET.get("is_detail_view", True)
    if is_detail_view == "False":
        is_detail_view = False
    elif is_detail_view == "True":
        is_detail_view = True
    todo_list = models.Todo.objects.all()

    def paginate(objects, num_page):
        paginator = Paginator(objects, num_page)
        pages = request.GET.get('page')
        try:
            local_page = paginator.page(pages)
        except PageNotAnInteger:
            local_page = paginator.page(1)
        except EmptyPage:
            local_page = paginator.page(paginator.num_pages)
        return local_page

    page = paginate(objects=todo_list, num_page=3)
    context = {
        "page": page,
        "is_detail_view": is_detail_view
    }
    return render(request, 'django_app/todo_list.html', context)


def todo_update(request, todo_id=None):
    if request.method == 'POST':
        todo = models.Todo.objects.get(id=todo_id)
        is_completed = request.POST.get("is_completed", "")

templates/django_app/home.html
{% extends "components/base.html" %}

{% block title %}Twitter Home{% endblock title %}
{% block main %}

{% endblock main %}

templates/django_app/post_list.html
{% load static %}

{% block main %}
        <link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#7952b3">
    {% block prestyles %}{% endblock prestyles %}
    <link href="signin.css" rel="stylesheet">
    <link href="/css/bootstrap.css" rel="stylesheet" crossorigin="anonymous">
    <link href="/fontawesome/css/all.css" rel="stylesheet" crossorigin="anonymous">
    <link href="/css/my2.css" rel="stylesheet" crossorigin="anonymous">
    <link href="{% static 'css/my2.css' %}" rel="stylesheet" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li style="margin-right: 15px;">
                        <img src="{{ user.profile.image.url }}" alt="Generic placeholder image" class="img-fluid " style="width: 50px; height: 50px; z-index: 1; border-radius: 100%; margin-top: 5px">
          {% if user.is_authenticated %}
            <a href="{% url 'django_app:profile' %}" type="button" class="btn btn-outline-Success me-2">Profile({{ user.username}})</a>
        {% else %}
            <a href="{% url 'django_app:profile' %}" type="button" class="btn btn-outline-primary me-2">Profile(anonymous)</a>
        {% endif %}
          </li>
        <li class="nav-item">
        <a href="{% url 'django_app:home_main' %}" class="btn btn-outline-primary" type="submit" style="margin-top: 9px; margin-right: 5px ">Home</a>
        <a href="{% url 'django_app:post_create' %}" class="btn btn-outline-primary" type="submit" style="margin-left: 15px; margin-top: 7px">Create new post</a>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <div class="text-end">
          {% if user.is_authenticated %}
              <a href="{% url 'django_app:logout' %}" type="button" class="btn btn-outline-danger me-2">Logout</a>
          {% else %}
              <a href="{% url 'django_app:login' %}" type="button" class="btn btn-outline-primary me-2">Login(anonymous)</a>
          {% endif %}
          </div>
      </form>
    </div>
  </div>
</nav>
<h1 align="center">All posts</h1>
    <a href="{% url 'django_app:post_list' %}" class="btn btn-success" type="submit" style="margin-left: 15px; margin-bottom: 15px">Go to all posts</a>
{% if page_posts %}
<form action="{% url 'django_app:post_list' %}"
    method="POST"
    enctype="multipart/form-data"
  >
      {% csrf_token %}
    <div class="input-group">
<input type="search" class="form-control p-3 w-50" placeholder="Search by names" name="search">
        <button class="btn btn-lg btn-primary" type="submit">Search</button>
    </div>
  </form>
    <div class="container container-fluid">

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          {% for post in page_posts %}
            <div class="col">
              <div class="card shadow-sm" style="border-radius: 30px;">
                <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false" style="border-radius: 30px;"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">{{ post.title }}</text></svg>
                <div class="card-header" align="center">{{ post.title }}</div>
                <div class="card-body">
                  <p class="card-text">{{ post.description }}</p>
                  <div class="d-flex justify-content-between align-items-center" >
                    <div class="btn-group">
                      <a href="{% url 'django_app:post_detail' post.id %}" type="button" class="btn btn-sm btn-outline-secondary">Details...</a>
                      <a href="#" type="button" class="btn btn-sm btn-outline-secondary">Edit</a>
                    </div>
                    <small class="text-muted">9 mins</small>
                  </div>
                    <small class="text-muted">
                        <a href="{% url 'django_app:post_delete' post.id %}" class="text-decoration-none btn"><i class="fa-solid fa-trash-can text-danger">Delete</i></a>
                    </small>
                    <div style="margin-left: 300px; border: 1px solid #E1C16E; text-align: center;">
                    {{ forloop.counter }}
                  </div>
                </div>
              </div>

            </div>

        {% endfor %}
      </div>
    </div>
    {% else %}
        {% include 'components/aborted.html' %}
    {% endif %}
{% include 'components/pagination_posts.html' %}
{% endblock main %}

templates/django_app/todo_list.html
{% load app_django_extras %}
{% load static %}


{% block head %}{% endblock head %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">

<div class="container-fluid">
<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarCollapse">
  <ul class="navbar-nav me-auto mb-2 mb-md-0">
                            <img src="{{ user.profile.image.url }}" alt="Generic placeholder image" class="img-fluid " style="width: 50px; height: 50px; z-index: 1; border-radius: 100%; margin-top: 5px">
        {% if user.is_authenticated %}
            <a href="{% url 'django_app:profile' %}" type="button" class="btn btn-outline-Success me-2" style="padding-top: 15px; margin-left:15px" >Profile({{ user.username}})</a>
        {% else %}
            <a href="{% url 'django_app:profile' %}" type="button" class="btn btn-outline-primary me-2" style="margin-left: 15px;">Profile(anonymous)</a>
        {% endif %}
    <a href="{% url 'django_app:home_main' %}" class="btn btn-outline-primary" type="submit" style="padding-left: 50px; padding-right: 50px;">Home</a>
    <a href="{% url 'django_app:post_create' %}" class="btn btn-outline-primary" type="submit" style="padding-left: 50px; padding-right: 50px; margin-left: 8px;">Tweet your tweet</a>
    <a href="{% url 'django_app:post_list' %}" class="btn btn-outline-primary" type="submit" style="padding-left: 50px; padding-right: 50px; margin-left: 15px;">All your posts</a>
    <a href="{% url 'django_app:todo_create' %}" class="btn btn-outline-primary" type="submit" style="padding-left: 50px; padding-right: 50px; margin-left: 15px;">Todo create</a>

  </ul>
  <form class="d-flex">
    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" style="margin-top: 15px">
    <div class="text-end">
      {% if user.is_authenticated %}
          <a href="{% url 'django_app:logout' %}" type="button" class="btn btn-outline-danger me-2" style="margin-top: 15px">Logout</a>
      {% else %}
          <a href="{% url 'django_app:login' %}" type="button" class="btn btn-outline-primary me-2">Login(anonymous)</a>
      {% endif %}
      </div>
  </form>
</div>
</div>
</nav>
<h1 align="center">All todos</h1>

<div align="center">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font_awesome_6_0_0/css/all.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font_zen/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
<link href="/css/my.css" rel="stylesheet" crossorigin="anonymous">
<link href="{% static 'css/my3.css' %}" rel="stylesheet" crossorigin="anonymous">
<div class="container shadow-lg custom-background-transparent-hard m-0 p-0" align="">
    <div class="shadow border-bottom m-0 p-0">
        <div class="d-flex justify-content-around">
            <h6 class="lead fw-bold m-1 p-2">todos <i class="btn btn-sm btn-dark bg-opacity-50 badge rounded-pill">{{ todo_count }}</i>:</h6>
            <a class="text-decoration-none btn btn-sm btn-success m-1 p-2" href="{% url 'django_app:todo_create' %}">
                <i class="fa-solid fa-circle-plus m-0 p-1"></i>
                create new todo
            </a>
        </div>
    </div>
    {% if page %}
    <div class="text-end">
        <form action="{% url 'django_app:todo_read_list' %}"
        method="GET"
        target="_self"
        enctype="multipart/form-data"
        name="idea_create"
        autocomplete="on"
        class="m-0 p-0"
        >
        {% csrf_token %}
        <div>
        <input type="hidden"
           name="is_detail_view"
           required=""
           placeholder=""
           {% if is_detail_view %}
                value="False"
           {% else %}
                value="True"
           {% endif %}
           minlength="1"
           maxlength="32"
           class="form-control form-control-sm"
        />
        </div>
        {% if is_detail_view %}
            <button class="btn btn-lg m-0 p-1" type="submit">
                <i class="fa-solid fa-list-check text-secondary m-0 p-1"></i>
                list view
            </button>
        {% else %}
            <button class="btn btn-lg m-0 p-1" type="submit">
                <i class="fa-solid fa-calendar-week text-secondary m-0 p-"></i>
                detail view
            </button>
        {% endif %}
        </form>
    </div>

    {% if page %}

        {% if is_detail_view %}
            <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3">
                {% for todo in page %}
                    <div class="col">
                        <div class="card border border-1 border-dark custom-background-transparent-middle m-1 p-0">
                            <div class="card-header">
                                <div class="m-0 p-3">
                                    <div class="d-flex justify-content-around">
                                        <a class="text-decoration-none text-dark" href="{% url 'django_app:todo_read' todo.id %}">
                                            <h5>{{ todo.title|cut_string:30 }}</h5>
                                        </a>
                                        <form action="{% url 'django_app:todo_update' todo.id %}"
                                              method="POST"
                                              target="_self"
                                              enctype="multipart/form-data"
                                              name="idea_create"
                                              autocomplete="on"
                                              class="m-0 p-0"
                                        >
                                            {% csrf_token %}
                                            <div>
                                                <input type="hidden"
                                                   name="is_completed"
                                                   required=""
                                                   placeholder=""
                                                   {% if todo.is_completed %}
                                                        value="False"
                                                   {% else %}
                                                        value="True"
                                                   {% endif %}
                                                   minlength="1"
                                                   maxlength="32"
                                                   class="form-control form-control-sm"
                                            />
                                            </div>
                                            <div class="btn-group m-0 p-1">
                                                {% if todo.is_completed %}
                                                    <button class="btn btn-sm btn-outline-danger m-0 p-1" type="submit">
                                                        <i class="fa-solid fa-circle-xmark text-danger m-0 p-1"></i>
                                                        not complete
                                                    </button>
                                                {% else %}
                                                    <button class="btn btn-sm btn-outline-success m-0 p-1" type="submit">
                                                        <i class="fa-solid fa-circle-check text-success m-0 p-1"></i>
                                                        complete
                                                    </button>
                                                {% endif %}
                                                <a href="{% url 'django_app:todo_delete' todo.id %}" class="btn btn-sm btn-outline-danger m-0 p-1">
                                                    <i class="fa-solid fa-circle-minus text-danger m-0 p-1"></i>
                                                    delete
                                                </a>
                                            </div>
                                        </form>
                                    </div>
                                    {% if todo.is_completed %}
                                        <div class="feature-icon bg-success bg-gradient text-white">
                                            <p class="m-0 p-1"></p>
                                        </div>
                                    {% else %}
                                        <div class="feature-icon bg-danger bg-gradient text-white">
                                            <p class="m-0 p-1"></p>
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="card-body">
                                <p class="m-0 p-3">{{ todo.description|cut_string:100 }}</p>
                            </div>
                            <div class="card-footer">
                                <div class="d-flex justify-content-between m-0 p-1">
                                    <small class="text-warning m-1 p-0">
                                        {{ todo.created }} [created]
                                    </small>
                                    <small class="text-success m-1 p-0">
                                        {{ todo.updated }} [updated]
                                    </small>
                                </div>
                                <a class="text-decoration-none text-dark" href="{% url 'django_app:todo_read' todo.id %}">
                                    <button class="btn btn-sm btn-outline-primary w-100 m-0 p-1" type="submit">
                                        <i class="fa-solid fa-circle-info m-0 p-1"></i>
                                        details
                                    </button>
                                </a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="m-0 p-1">
                <ul class="m-0">
                    {% for todo in page %}
                        <li class="text-start m-0 p-0 border border-1 border-dark p-1">
                            {% if todo.is_completed %}
                                <div class="feature-icon bg-success d-flex justify-content-between">
                            {% else %}
                                <div class="feature-icon bg-danger d-flex justify-content-between">
                            {% endif %}
                                <a class="text-decoration-none text-white small w-50" href="{% url 'django_app:todo_read' todo.id %}">
                                    <div class="d-flex">
                                        <h6 class="lead m-1 p-1">{{ todo.description|cut_string:20 }}</h6>
                                        <small class="m-0 p-2">{{ todo.description|cut_string:30 }}</small>
                                    </div>
                                </a>
                                <div class="m-1 p-1">
                                    <small class="text-white m-1 p-0">
                                        {{ todo.updated }} [updated]
                                    </small>
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

        <div class="container d-flex justify-content-center align-self-center">
            {% include 'components/pagination_todos.html' %}
        </div>
    {% endif %}
{% else %}
        {% include 'components/aborted.html' %}
    {% endif %}
</div>
</div>