ads/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('ad_list/', views.ad_list, name='ad_list'),
    path('ad_create/', views.ad_create, name='ad_create'),
    path('ad/<int:pk>/delete/', views.ad_delete, name='ad_delete'),
]

django_app/urls.py
from django.urls import path, re_path
from django_app import views

app_name = 'django_app'
urlpatterns = [
    path('', views.home_view, name=''),
    path('index/', views.HomeView.as_view(), name='index'),
    path('home/', views.HomeView.as_view(), name='home'),
    path('home_main/', views.home_main, name='home_main'),


    path('register/', views.register, name='register'),
    path('login/', views.login_, name='login'),
    path('logout/', views.logout_f, name='logout'),


    # path('post/ratings/', views.posts),
    path('post_list/', views.post_list, name='post_list'),
    path('post/<int:pk>/delete/', views.post_delete, name='post_delete'),
    path('post/<int:pk>/detail/', views.post_detail, name='post_detail'),
    path('post/<int:pk>/comment/delete/', views.post_comment_delete, name='post_comment_delete'),
    path('post_create/', views.post_create, name='post_create'),

    path('profile/', views.profile, name='profile'),
    path('profile_update/', views.profileupdate, name='profile_update'),

    path('post_comment_create/<int:pk>/', views.post_comment_create, name='post_comment_create'),

    path('todo/create/', views.todo_create, name='todo_create'),
    path('todo/<int:todo_id>/', views.todo_read, name='todo_read'),
    path('todo/list/', views.todo_read_list, name='todo_read_list'),
    path('todo/<int:todo_id>/update/', views.todo_update, name='todo_update'),
    re_path(r'^todo/(?P<todo_id>\d+)/delete/$', views.todo_delete, name='todo_delete'),

]

django_settings/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),  # grappelli URLS

    path('admin/', admin.site.urls),

    path('', include('django_app.urls')),
    path('', include('ads.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/components/aborted.html
<hr/>
<div class="container">
    <div class="container-fluid">
        <p class="lead text-center text-danger">Not have any data!</p>
    </div>
</div>
<hr/>

templates/components/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <hr/>
        <div class="container">
            <div class="container-fluid">
                <p class="lead text-center text-danger">Error: {{ detail }} ({{ extra }})</p>
            </div>
        </div>
    <hr/>
</body>
</html>

templates/components/footer.html
<footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
    </ul>
    <p class="text-center text-muted">© 2022 Company, Inc</p>
</footer>

templates/components/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">

<div class="container-fluid">
<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarCollapse">
  <ul class="navbar-nav me-auto mb-2 mb-md-0">
                            <img src="{{ user.profile.image.url }}" alt="Generic placeholder image" class="img-fluid " style="width: 50px; height: 50px; z-index: 1; border-radius: 100%;">
        {% if user.is_authenticated %}
            <a href="{% url 'django_app:profile' %}" type="button" class="btn btn-outline-Success me-2" style="padding-top: 15px;">Profile({{ user.username}})</a>
        {% else %}
            <a href="{% url 'django_app:profile' %}" type="button" class="btn btn-outline-primary me-2">Profile(anonymous)</a>
        {% endif %}
    <a href="{% url 'django_app:post_create' %}" class="btn btn-outline-primary" type="submit" style="padding-left: 50px; padding-right: 50px;">Tweet your first tweet</a>
    <a href="{% url 'django_app:post_list' %}" class="btn btn-outline-primary" type="submit" style="padding-left: 50px; padding-right: 50px; margin-left: 15px;">All your posts</a>
    <a href="{% url 'django_app:todo_create' %}" class="btn btn-outline-primary" type="submit" style="padding-left: 50px; padding-right: 50px; margin-left: 15px;">Todo create</a>
    <a href="{% url 'django_app:todo_list' %}" class="btn btn-outline-primary" type="submit" style="padding-left: 50px; padding-right: 50px; margin-left: 15px; margin-right: 25px;">Todo list</a>
  </ul>
  <form class="d-flex">
    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
    <div class="text-end">
      {% if user.is_authenticated %}
          <a href="{% url 'django_app:logout' %}" type="button" class="btn btn-outline-danger me-2">Logout</a>
      {% else %}
          <a href="{% url 'django_app:login' %}" type="button" class="btn btn-outline-primary me-2">Login(anonymous)</a>
      {% endif %}
      </div>
  </form>
</div>
</div>
</nav>

templates/components/pagination_ads.html
<div style="margin-top: 15px;">
        <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center">
          {% if page_ads.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_ads.previous_page_number }}" tabindex="-1" aria-disabled="true">Previous</a>
        </li>
          {% endif %}
          {% if page_ads.number != 1 %}
        <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
          {% endif %}
        <li class="page-item"><a class="page-link" href="#">{{ page_ads.number }} страница из {{ page_ads.paginator.num_pages}}</a></li>
          {% if page_ads.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_ads.next_page_number }}">Next</a>
        </li>
          {% endif %}
      </ul>
    </nav>
</div>

templates/components/pagination_posts.html
<div style="margin-top: 15px;">
        <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center">
          {% if page_posts.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_posts.previous_page_number }}" tabindex="-1" aria-disabled="true">Previous</a>
        </li>
          {% endif %}
          {% if page_posts.number != 1 %}
        <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
          {% endif %}
        <li class="page-item"><a class="page-link" href="#">{{ page_posts.number }} страница из {{ page_posts.paginator.num_pages}}</a></li>
          {% if page_posts.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_posts.next_page_number }}">Next</a>
        </li>
          {% endif %}
      </ul>
    </nav>
</div>

templates/components/pagination_todos.html
<div style="margin-top: 15px;">
        <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center">
          {% if page.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page.previous_page_number }}" tabindex="-1" aria-disabled="true">Previous</a>
        </li>
          {% endif %}
          {% if page.number != 1 %}
        <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
          {% endif %}
        <li class="page-item"><a class="page-link" href="#">{{ page.number }} страница из {{ page.paginator.num_pages}}</a></li>
          {% if page.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page.next_page_number }}">Next</a>
        </li>
          {% endif %}
      </ul>
    </nav>
</div>

templates/components/title.html
<h1 align="center">Home page</h1>